channels:
- conda-forge
dependencies:
- python=3.11.13
- pip<=25.2
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - opt-einsum==3.4.0
  - pandas==2.3.3
  - torch==2.9.0
  - tqdm==4.67.1
name: mlflow-env
